### ISSUE TITLE
About the "compute_scores_all_target" function

### ISSUE THREAD

**Issue by zhaoxin94** [silvia1993/ROS#4]
Hi, thanks very much for your impressive work about OSDA.

I can't fully understand the code here https://github.com/silvia1993/ROS/blob/bceef4d9dc505f55322a4c25fb8071f49e7a5671/code/compute_score.py#L128-L136

In your code, the  'num_low' represents the number of the normal target samples which scores are above the threshold value. So, the name is  a little confusing, and I think it's better to call it 'num_high'.

And why you make the 'select_high' and 'select_low' both equal to 'num_low'? I think select_low should be equal to (len_target - num_low) which is more consistent with the paper.

I don’t know if I misunderstood the code. Thanks very much and hope to get your reply.

**Comment by silvia1993** [comment]
Hi @zhaoxin94,

You correctly understood this part of the code: we use the same amount of images for both "select_high" and "select_low".
One of the main problem in OSDA is in the choice of a good threshold for the known/unknown separation. The risk is always that the Target samples with a score not so high/low are wrongly considered as known/unknown. 
We found out that a good way to prevent this situation is to remove from the selection the Target samples with the most  ambiguous score. So, using the same number of samples for the known and unknown subsets we prevent the selection of uncertain samples without adding extra hyperparameters. 

I hope that this answers your questions!

**Comment by zhaoxin94** [comment]
Hi @silvia1993,

Thanks very much for your quick reply. I understand your consideration of selecting target samples with confident scores.

But I have another concern with this operation.  

When the known samples in the target domain are very scarce, that is the openness approaches 1. In this extreme situation, most samples belong to unknown classes, so the mean score (threshold) will be small. Won't this make the unknown samples be wrongly classified as known samples?

Moreover, When the unknown samples in the target domain are very scarce, that is, the openness approaches 0. In this extreme situation, most samples belong to known classes, so many samples will be selected as known samples.  Due to the sample value of 'select_high' and 'select_low', this may make some known samples be wrongly classified as unknown samples?

Do you have any comments on my concern?

Thanks very much and hope to get your reply.

**Comment by silvia1993** [comment]
Hi @zhaoxin94,

in the extreme situations you described our procedure could fail, but we demonstrate in the experiments that also increasing the degree of openness our approach still works well. Your concern is legitimate, but observing the results we can conclude that the way in which we designed the known/unknown separation of the Target samples represents a good compromise.

Hope this helps!

**Comment by zhaoxin94** [comment]
Thank you for your answer！
